[package]
name = "hello"
edition = "2021"
version = "0.0.0"
publish = false

[dependencies.rocket]
version = "0.5"
features = ["json"]

[dependencies]
serde = { version = "~1.0", features = ["derive"] }
rand = "0.9.0"